baseURL = 'https://ssongjay.github.io/few-words-blog/'
languageCode = 'ko-kr'
title = 'a few words'
theme = 'PaperMod'

[params]
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  description = '오래 다시 보지 않기 위한 몇 개의 단어들'

[params.homeInfoParams]
  Title = 'a few words'
  Content = '오래 다시 보지 않기 위한 몇 개의 단어들'
